accounts/urls.py
"""
Urls for the accounts app.
"""

from django.urls import path
from .views import RegisterView, LoginView

from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy

app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('accounts:login')), name='logout'),
]

blog_app/urls.py
"""
Urls for the blog_app app.
"""

from django.urls import path
from .views import home, post_detail, cine, tv, videojuegos, literatura, podcasts

from . import views

app_name = 'blog_app'

urlpatterns = [
    path('', home.as_view(), name='home'),
    path('post/<int:pk>/', post_detail.as_view(), name='post_detail'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('cine/', cine.as_view(), name='cine'),
    path('tv/', tv.as_view(), name='tv'),
    path('videojuegos/', videojuegos.as_view(), name='videojuegos'),
    path('literatura/', literatura.as_view(), name='literatura'),
    path('podcasts/', podcasts.as_view(), name='podcasts'),
    path('about/', views.about, name='about'),
    path('search/', views.search, name='search'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('', include('blog_app.urls')),
]

blog_app/models.py
"""
Model definitions for the blog_app app.
"""

from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model

User = get_user_model()


class Category(models.Model):
    """ Model definition for the Category model. """
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Tag(models.Model):
    """ Model definition for the Tag model. """
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Post(models.Model):
    """ Model definition for the Post model. """
    title = models.CharField(max_length=200)
    description = models.TextField()
    text = models.TextField()
    publish_date = models.DateTimeField(default=timezone.now)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title

class Comment(models.Model):
    """ Model definition for the Comment model. """
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.text

blog_app/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

class SearchForm(forms.Form):
    query = forms.CharField(max_length=100)

blog_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView
from .models import Post, Category, Comment
from .forms import CommentForm, SearchForm

class home(ListView):
    model = Post
    template_name = 'blog_app/home.html'
    context_object_name = 'posts'
    paginate_by = 3
    ordering = ['-publish_date']

class post_detail(DetailView):
    model = Post
    template_name = 'blog_app/post_detail.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm()
        context['comments'] = Comment.objects.filter(post=self.object)
        return context

class cine(ListView):
    model = Post
    template_name = 'blog_app/cine.html'
    context_object_name = 'posts'
    paginate_by = 6
    ordering = ['-publish_date']

    def get_queryset(self):
        cine_category = Category.objects.get(name='Cine')
        return Post.objects.filter(category=cine_category).order_by('-publish_date')

class tv(ListView):
    model = Post
    template_name = 'blog_app/tv.html'
    context_object_name = 'posts'
    paginate_by = 6
    ordering = ['-publish_date']

    def get_queryset(self):
        tv_category = Category.objects.get(name='TV')
        return Post.objects.filter(category=tv_category).order_by('-publish_date')

class videojuegos(ListView):
    model = Post
    template_name = 'blog_app/videojuegos.html'
    context_object_name = 'posts'
    paginate_by = 6
    ordering = ['-publish_date']

    def get_queryset(self):
        videojuegos_category = Category.objects.get(name='Videojuegos')
        return Post.objects.filter(category=videojuegos_category).order_by('-publish_date')

class literatura(ListView):
    model = Post
    template_name = 'blog_app/literatura.html'
    context_object_name = 'posts'
    paginate_by = 6
    ordering = ['-publish_date']

    def get_queryset(self):
        literatura_category = Category.objects.get(name='Literatura') #literatura_category
        return Post.objects.filter(category=literatura_category).order_by('-publish_date')

class podcasts(ListView):
    model = Post
    template_name = 'blog_app/podcasts.html'
    context_object_name = 'posts'
    paginate_by = 6
    ordering = ['-publish_date']

    def get_queryset(self):
        podcasts_category = Category.objects.get(name='Podcasts')
        return Post.objects.filter(category=podcasts_category).order_by('-publish_date')

def about(request):
    return render(request, 'blog_app/about.html')

def search(request):
    if request.method == 'GET':
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data.get('query')
            results = Post.objects.filter(title__icontains=query)
            return render(request, 'blog_app/search.html', {'results': results, 'query': query})
    else:
        form = SearchForm()
    return render(request, 'blog_app/search.html', {'form': form})

@require_POST
def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.author = request.user
        comment.save()
    return redirect('blog_app:post_detail', pk=post.pk)

blog_app/templates/blog_app/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Acerca de{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/about.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <section>
            <h2>Our Mission</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in arcu nec ex ultricies tincidunt.
                Curabitur consequat fermentum odio, ut dictum nisi bibendum a. Vestibulum euismod ligula non nunc
                venenatis, at vehicula orci gravida.</p>
        </section>

        <section>
            <h2>Our Team</h2>
            <div class="team-member">
                <img src="{% static 'img/john.avif' %}" alt="CEO" class="team-image" width="200" height="200">
                <h3>John Doe</h3>
                <p>CEO</p>
            </div>
            <div class="team-member">
                <img src="{% static 'img/jane.avif' %}" alt="Marketing Manager" class="team-image" width="200" height="200">
                <h3>Jane Smith</h3>
                <p>Marketing Manager</p>
            </div>
        </section>
        <section>
            <h2>Contact Us</h2>
            <p>Email: info@example.com</p>
            <p>Phone: 123-456-7890</p>
            <p>Address: 123 Main Street, City, Country</p>
        </section>
    </div>
{% endblock %}

blog_app/templates/blog_app/cine.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Cine{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}

{% block content %}
{% for post in posts %}
    <section class="section">
        <h2 class="title">{{ post.title }}</h2>
        <h4 class="subtitle">{{ post.description }}</h4>
        <h5 class="date">{{ post.publish_date }}</h5>
        <h5 class="author">by Author</h5>
        <p class="text">{{ post.text|truncatechars:200 }}</p>
        <a class="link" href="{% url 'blog_app:post_detail' post.id %}">Seguir leyendo...</a>
    </section>
{% endfor %}
<div class="pagination">
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; Anteriores</a>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <span class="current">{{ num }}</span>
            {% else %}
                <a href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Siguientes &raquo;</a>
        {% endif %}
    {% endif %}
</div>
{% endblock %}

blog_app/templates/blog_app/home.html
{% extends 'base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}

{% block content %}
{% for post in posts %}
    <section class="section">
        <h2 class="title">{{ post.title }}</h2>
        <h4 class="subtitle">{{ post.description }}</h4>
        <h5 class="date">{{ post.publish_date }}</h5>
        <h5 class="author">by Author</h5>
        <p class="text">{{ post.text|truncatechars:200 }}</p>
        <a class="link" href="{% url 'blog_app:post_detail' post.id %}">Seguir leyendo...</a>
    </section>
    <br>
{% endfor %}
<div class="pagination">
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; Anteriores</a>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <span class="current">{{ num }}</span>
            {% else %}
                <a href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Siguientes &raquo;</a>
        {% endif %}
    {% endif %}
</div>
{% endblock %}

blog_app/templates/blog_app/literatura.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Literatura{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}

{% block content %}
{% for post in posts %}
    <section class="section">
        <h2 class="title">{{ post.title }}</h2>
        <h4 class="subtitle">{{ post.description }}</h4>
        <h5 class="date">{{ post.publish_date }}</h5>
        <h5 class="author">by Author</h5>
        <p class="text">{{ post.text|truncatechars:200 }}</p>
        <a class="link" href="{% url 'blog_app:post_detail' post.id %}">Seguir leyendo...</a>
    </section>
{% endfor %}
<div class="pagination">
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; Anteriores</a>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <span class="current">{{ num }}</span>
            {% else %}
                <a href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Siguientes &raquo;</a>
        {% endif %}
    {% endif %}
</div>
{% endblock %}

blog_app/templates/blog_app/podcasts.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Podcasts{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}

{% block content %}
{% for post in posts %}
    <section class="section">
        <h2 class="title">{{ post.title }}</h2>
        <h4 class="subtitle">{{ post.description }}</h4>
        <h5 class="date">{{ post.publish_date }}</h5>
        <h5 class="author">by Author</h5>
        <p class="text">{{ post.text|truncatechars:200 }}</p>
        <a class="link" href="{% url 'blog_app:post_detail' post.id %}">Seguir leyendo...</a>
    </section>
{% endfor %}
<div class="pagination">
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; Anteriores</a>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <span class="current">{{ num }}</span>
            {% else %}
                <a href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Siguientes &raquo;</a>
        {% endif %}
    {% endif %}
</div>
{% endblock %}

blog_app/templates/blog_app/post_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ post.title }}{% endblock %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}

{% block content %}
    <section class="section">
        <h2 class="title">{{ post.title }}</h2>
        <h4 class="subtitle">{{ post.description }}</h4>
        <h5 class="date">{{ post.publish_date }}</h5>
        <h5 class="author">by Author</h5>
        <p class="text">{{ post.text|linebreaks }}</p>
    </section>

    {% if user.is_authenticated %}
        <section class="section">
            <h2 class="title">Comments</h2>
            <form method="post" action="{% url 'blog_app:add_comment_to_post' post.pk %}">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Comment</button>
            </form>
        </section>
    {% else %}
        <section class="section">
            <p>You must <a href="{% url 'accounts:login' %}">login</a> to comment</p>
        </section>
    {% endif %}

    <section class="section">
        <h3 class="title">Comments</h3>
        <ul class="comments">
            {% for comment in comments %}
                <li class="comment_author">{{ comment.author }} - {{ comment.created_date|date:"d/m/Y" }}</li>
                <li class="comment">{{ comment.text }}</li>
            {% endfor %}
        </ul>
    </section>
{% endblock %}

blog_app/templates/blog_app/search.html
{% extends 'base.html' %}

{% block title %}Search{% endblock %}

{% block content %}
    <section>
        <h2>Resultados de búsqueda para "{{ query }}"</h2>
        <ul>
            {% for post in results %}
            <li><a href="{% url 'blog_app:post_detail' post.id %}">{{ post.title }}</a></li>
            {% empty %}
            <li>No se encontraron resultados.</li>
            {% endfor %}
        </ul>
    </section>
{% endblock %}

blog_app/templates/blog_app/tv.html
{% extends 'base.html' %}
{% load static %}

{% block title %}TV{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}

{% block content %}
{% for post in posts %}
    <section class="section">
        <h2 class="title">{{ post.title }}</h2>
        <h4 class="subtitle">{{ post.description }}</h4>
        <h5 class="date">{{ post.publish_date }}</h5>
        <h5 class="author">by Author</h5>
        <p class="text">{{ post.text|truncatechars:200 }}</p>
        <a class="link" href="{% url 'blog_app:post_detail' post.id %}">Seguir leyendo...</a>
    </section>
{% endfor %}
<div class="pagination">
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; Anteriores</a>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <span class="current">{{ num }}</span>
            {% else %}
                <a href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Siguientes &raquo;</a>
        {% endif %}
    {% endif %}
</div>
{% endblock %}

blog_app/templates/blog_app/videojuegos.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Videojuegos{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}

{% block content %}
{% for post in posts %}
    <section class="section">
        <h2 class="title">{{ post.title }}</h2>
        <h4 class="subtitle">{{ post.description }}</h4>
        <h5 class="date">{{ post.publish_date }}</h5>
        <h5 class="author">by Author</h5>
        <p class="text">{{ post.text|truncatechars:200 }}</p>
        <a class="link" href="{% url 'blog_app:post_detail' post.id %}">Seguir leyendo...</a>
    </section>
{% endfor %}
<div class="pagination">
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; Anteriores</a>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <span class="current">{{ num }}</span>
            {% else %}
                <a href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Siguientes &raquo;</a>
        {% endif %}
    {% endif %}
</div>
{% endblock %}